# =============================================================================
# efs.tf — EFS Shared Volume (Agent ↔ OpenROAD runner)
# =============================================================================
# Shared filesystem for:
#   /shared/reports/  — OpenROAD dumps timing/DRC reports here
#   /shared/designs/  — Training designs (gcd, ibex, aes with sky130)
#   /shared/scripts/  — ECO Tcl scripts generated by agent
#
# Cost: ~$0.30/GB-month (Infrequent Access), ~$0.01-0.02/month at demo scale
# =============================================================================

resource "aws_efs_file_system" "shared" {
  creation_token   = "${var.project_name}-shared"
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
  encrypted        = true

  lifecycle_policy {
    transition_to_ia = "AFTER_14_DAYS"
  }

  tags = {
    Name = "${var.project_name}-shared-efs"
  }
}

resource "aws_efs_mount_target" "shared" {
  count = 2

  file_system_id  = aws_efs_file_system.shared.id
  subnet_id       = aws_subnet.public[count.index].id
  security_groups = [aws_security_group.efs.id]
}

# ---------------------------------------------------------------------------
# EFS Access Point — /shared directory
# ---------------------------------------------------------------------------

resource "aws_efs_access_point" "shared" {
  file_system_id = aws_efs_file_system.shared.id

  posix_user {
    gid = 1000
    uid = 1000
  }

  root_directory {
    path = "/shared"
    creation_info {
      owner_gid   = 1000
      owner_uid   = 1000
      permissions = "755"
    }
  }

  tags = {
    Name = "${var.project_name}-shared-ap"
  }
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------

output "efs_file_system_id" {
  description = "EFS file system ID"
  value       = aws_efs_file_system.shared.id
}

output "efs_access_point_id" {
  description = "EFS access point ID for /shared"
  value       = aws_efs_access_point.shared.id
}
