# S3 Bucket for Timing Dashboards
#
# Hosts static HTML dashboard files generated by report_visualizer.py
# Files are served via CloudFront CDN for fast global access
#
# Cost: ~$0.10-0.50/month

resource "aws_s3_bucket" "dashboards" {
  bucket = "${var.project_name}-dashboards-${var.environment}"

  tags = {
    Name        = "IP Design Agent Dashboards"
    Environment = var.environment
    ManagedBy   = "Terraform"
    Purpose     = "Timing closure dashboard hosting"
  }
}

# Block public access (CloudFront will serve via OAI)
resource "aws_s3_bucket_public_access_block" "dashboards" {
  bucket = aws_s3_bucket.dashboards.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Versioning for dashboard files (optional but good practice)
resource "aws_s3_bucket_versioning" "dashboards" {
  bucket = aws_s3_bucket.dashboards.id

  versioning_configuration {
    status = "Enabled"
  }
}

# Lifecycle policy to delete old versions after 30 days
resource "aws_s3_bucket_lifecycle_configuration" "dashboards" {
  bucket = aws_s3_bucket.dashboards.id

  rule {
    id     = "delete-old-versions"
    status = "Enabled"
    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }

  rule {
    id     = "delete-old-reports"
    status = "Enabled"
    filter {}

    expiration {
      days = 90
    }
  }
}

# CORS configuration (for API access)
resource "aws_s3_bucket_cors_configuration" "dashboards" {
  bucket = aws_s3_bucket.dashboards.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "HEAD"]
    allowed_origins = ["*"]  # In production, restrict to your domain
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# Bucket policy for CloudFront access
resource "aws_s3_bucket_policy" "dashboards" {
  bucket = aws_s3_bucket.dashboards.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "CloudFrontAccess"
        Effect = "Allow"
        Principal = {
          AWS = aws_cloudfront_origin_access_identity.dashboards.iam_arn
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.dashboards.arn}/*"
      },
      {
        Sid    = "ECSTaskUpload"
        Effect = "Allow"
        Principal = {
          AWS = aws_iam_role.ecs_task.arn
        }
        Action = [
          "s3:PutObject",
          "s3:GetObject",
          "s3:DeleteObject",
          "s3:ListBucket"
        ]
        Resource = [
          "${aws_s3_bucket.dashboards.arn}/*",
          aws_s3_bucket.dashboards.arn
        ]
      }
    ]
  })

  depends_on = [
    aws_s3_bucket_public_access_block.dashboards
  ]
}

# Upload sample dashboard (for initial testing)
resource "aws_s3_object" "sample_dashboard" {
  bucket       = aws_s3_bucket.dashboards.id
  key          = "sample_timing_dashboard.html"
  source       = "${path.module}/../reports/sample_timing_dashboard.html"
  content_type = "text/html"
  etag         = filemd5("${path.module}/../reports/sample_timing_dashboard.html")

  # Cache control headers
  cache_control = "public, max-age=3600"  # 1 hour cache

  tags = {
    Name = "Sample Timing Dashboard"
    Type = "Dashboard"
  }
}

# Upload index.html (listing page)
resource "aws_s3_object" "dashboard_index" {
  bucket       = aws_s3_bucket.dashboards.id
  key          = "index.html"
  content_type = "text/html"

  content = <<-HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>IP Design Agent - Timing Dashboards</title>
<style>
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 40px;
  margin: 0;
}
.container {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  padding: 40px;
  border-radius: 12px;
  box-shadow: 0 8px 16px rgba(0,0,0,0.2);
}
h1 { color: #2d3748; margin-bottom: 8px; }
.subtitle { color: #718096; margin-bottom: 32px; }
.dashboard-list { list-style: none; padding: 0; }
.dashboard-item {
  padding: 16px;
  margin-bottom: 12px;
  background: #f7fafc;
  border-radius: 8px;
  border-left: 4px solid #667eea;
}
.dashboard-item a {
  color: #667eea;
  text-decoration: none;
  font-weight: 600;
  font-size: 18px;
}
.dashboard-item a:hover {
  text-decoration: underline;
}
.dashboard-desc {
  color: #718096;
  font-size: 14px;
  margin-top: 4px;
}
.badge {
  display: inline-block;
  padding: 4px 12px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: 600;
  background: #c6f6d5;
  color: #22543d;
  margin-left: 8px;
}
</style>
</head>
<body>
<div class="container">
  <h1>IP Design Agent - Timing Dashboards</h1>
  <div class="subtitle">Visual timing closure validation for EDA flows</div>

  <ul class="dashboard-list">
    <li class="dashboard-item">
      <a href="sample_timing_dashboard.html">Sample: gcd (sky130hd)</a>
      <span class="badge">DEMO</span>
      <div class="dashboard-desc">
        3-run ECO workflow showing WNS improvement from -0.52ns → +0.08ns
      </div>
    </li>
  </ul>

  <div style="margin-top: 32px; padding-top: 32px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 14px;">
    <strong>About:</strong> This dashboard system tracks timing metrics across multiple ECO iterations,
    providing visual validation of improvements. Built with Python, Plotly, and deployed on AWS.
    <br><br>
    <strong>Agent:</strong> ip-design-agent v3.0 |
    <strong>Region:</strong> ${var.aws_region} |
    <strong>Environment:</strong> ${var.environment}
  </div>
</div>
</body>
</html>
HTML

  cache_control = "public, max-age=300"  # 5 minutes

  tags = {
    Name = "Dashboard Index"
    Type = "Index"
  }
}

# Output bucket details
output "dashboard_bucket_name" {
  description = "S3 bucket name for dashboards"
  value       = aws_s3_bucket.dashboards.id
}

output "dashboard_bucket_arn" {
  description = "S3 bucket ARN"
  value       = aws_s3_bucket.dashboards.arn
}
